baseurl: /buffalo
permalink: pretty
markdown: kramdown
paginate: 5
repo: buffalo
github_org: maptime
maptime:
  chapter: MaptimeBUF
  twitter: MaptimeBUF
  #disqus: YOUR DISQUS USERNAME
future: false
